import type { CategoryFilter, GlobalStats, TorrentItem, TrackerGroup } from "./types";

function isoFiles(prefix: string, sizeLabel: string): TorrentItem["files"] {
  return [
    {
      id: `${prefix}-1`,
      name: `${prefix}.iso`,
      size: sizeLabel,
      progress: 1,
      priority: "high",
      wanted: true,
    },
    {
      id: `${prefix}-2`,
      name: "README.html",
      size: "12 KB",
      progress: 1,
      priority: "normal",
      wanted: true,
    },
  ];
}

export const DOWNLOADS_GLOBAL_STATS: GlobalStats = {
  clientVersion: "Transmission 4.0.6 (Arco stub)",
  host: "Paul’s MacBook",
  globalDownSpeed: "2.4 MB/s",
  globalUpSpeed: "128 KB/s",
  freeSpace: "142 GB",
  totalSize: "28.6 GB",
};

export const DOWNLOADS_MOCK: TorrentItem[] = [
  {
    id: "t-ubuntu-2404",
    name: "ubuntu-24.04.2-desktop-amd64.iso",
    size: "5.7 GB",
    sizeBytes: 5_700_000_000,
    progress: 0.62,
    status: "downloading",
    seeds: { connected: 18, total: 142 },
    peers: { connected: 42, total: 88 },
    downSpeed: "1.8 MB/s",
    upSpeed: "12 KB/s",
    ratio: 0.04,
    uploaded: "18.2 MB",
    downloaded: "3.5 GB",
    remaining: "2.2 GB",
    wasted: "0 B",
    tracker: "https://torrent.ubuntu.com/announce",
    trackerUpdate: "2 min ago",
    lastActive: "now",
    maxPeers: 80,
    downLimit: "Unlimited",
    upLimit: "50 KB/s",
    error: null,
    addedAt: "2026-07-05T14:22:00Z",
    trackers: [
      {
        id: "tr-ubuntu",
        url: "https://torrent.ubuntu.com/announce",
        status: "working",
        lastAnnounce: "2 min ago",
        seeders: 142,
        leechers: 88,
      },
    ],
    peersList: [
      {
        id: "p1",
        address: "203.0.113.42:51413",
        client: "Transmission 4.0",
        progress: 1,
        downSpeed: "420 KB/s",
        upSpeed: "0 B/s",
        flags: "I",
      },
    ],
    files: isoFiles("ubuntu-24.04.2-desktop-amd64", "5.7 GB"),
  },
  {
    id: "t-fedora-workstation",
    name: "Fedora-Workstation-Live-x86_64-42-1.1.iso",
    size: "2.1 GB",
    sizeBytes: 2_100_000_000,
    progress: 1,
    status: "seeding",
    seeds: { connected: 0, total: 56 },
    peers: { connected: 3, total: 12 },
    downSpeed: "0 B/s",
    upSpeed: "86 KB/s",
    ratio: 2.14,
    uploaded: "4.5 GB",
    downloaded: "2.1 GB",
    remaining: "0 B",
    wasted: "0 B",
    tracker: "http://torrent.fedoraproject.org:6969/announce",
    trackerUpdate: "8 min ago",
    lastActive: "now",
    maxPeers: 50,
    downLimit: "Unlimited",
    upLimit: "Unlimited",
    error: null,
    addedAt: "2026-07-01T09:10:00Z",
    trackers: [
      {
        id: "tr-fedora",
        url: "http://torrent.fedoraproject.org:6969/announce",
        status: "working",
        lastAnnounce: "8 min ago",
        seeders: 56,
        leechers: 12,
      },
    ],
    peersList: [],
    files: isoFiles("Fedora-Workstation-Live-x86_64-42-1.1", "2.1 GB"),
  },
  {
    id: "t-debian-netinst",
    name: "debian-12.9.0-amd64-netinst.iso",
    size: "659 MB",
    sizeBytes: 659_000_000,
    progress: 0.18,
    status: "downloading",
    seeds: { connected: 6, total: 34 },
    peers: { connected: 14, total: 41 },
    downSpeed: "512 KB/s",
    upSpeed: "4 KB/s",
    ratio: 0.01,
    uploaded: "120 KB",
    downloaded: "118 MB",
    remaining: "541 MB",
    wasted: "0 B",
    tracker: "http://bt.debian.org:80/announce",
    trackerUpdate: "1 min ago",
    lastActive: "now",
    maxPeers: 60,
    downLimit: "Unlimited",
    upLimit: "Unlimited",
    error: null,
    addedAt: "2026-07-06T15:40:00Z",
    trackers: [
      {
        id: "tr-debian",
        url: "http://bt.debian.org:80/announce",
        status: "working",
        lastAnnounce: "1 min ago",
        seeders: 34,
        leechers: 41,
      },
    ],
    peersList: [],
    files: isoFiles("debian-12.9.0-amd64-netinst", "659 MB"),
  },
  {
    id: "t-archlinux",
    name: "archlinux-2026.07.01-x86_64.iso",
    size: "1.3 GB",
    sizeBytes: 1_300_000_000,
    progress: 1,
    status: "paused",
    seeds: { connected: 0, total: 22 },
    peers: { connected: 0, total: 0 },
    downSpeed: "0 B/s",
    upSpeed: "0 B/s",
    ratio: 0.92,
    uploaded: "1.2 GB",
    downloaded: "1.3 GB",
    remaining: "0 B",
    wasted: "0 B",
    tracker: "http://tracker.archlinux.org:6969/announce",
    trackerUpdate: "1 h ago",
    lastActive: "45 min ago",
    maxPeers: 40,
    downLimit: "Unlimited",
    upLimit: "Unlimited",
    error: null,
    addedAt: "2026-06-28T11:00:00Z",
    trackers: [
      {
        id: "tr-arch",
        url: "http://tracker.archlinux.org:6969/announce",
        status: "working",
        lastAnnounce: "1 h ago",
        seeders: 22,
        leechers: 4,
      },
    ],
    peersList: [],
    files: isoFiles("archlinux-2026.07.01-x86_64", "1.3 GB"),
  },
  {
    id: "t-opensuse",
    name: "openSUSE-Tumbleweed-DVD-x86_64-Current.iso",
    size: "4.4 GB",
    sizeBytes: 4_400_000_000,
    progress: 0,
    status: "queued",
    seeds: { connected: 0, total: 18 },
    peers: { connected: 0, total: 0 },
    downSpeed: "0 B/s",
    upSpeed: "0 B/s",
    ratio: 0,
    uploaded: "0 B",
    downloaded: "0 B",
    remaining: "4.4 GB",
    wasted: "0 B",
    tracker: "http://tracker.opensuse.org:6969/announce",
    trackerUpdate: "—",
    lastActive: "—",
    maxPeers: 50,
    downLimit: "Unlimited",
    upLimit: "Unlimited",
    error: null,
    addedAt: "2026-07-06T16:00:00Z",
    trackers: [
      {
        id: "tr-opensuse",
        url: "http://tracker.opensuse.org:6969/announce",
        status: "updating",
        lastAnnounce: "—",
        seeders: 18,
        leechers: 9,
      },
    ],
    peersList: [],
    files: isoFiles("openSUSE-Tumbleweed-DVD-x86_64-Current", "4.4 GB"),
  },
  {
    id: "t-manjaro",
    name: "manjaro-kde-24.2.1-240726-linux612.iso",
    size: "3.6 GB",
    sizeBytes: 3_600_000_000,
    progress: 0.94,
    status: "checking",
    seeds: { connected: 2, total: 31 },
    peers: { connected: 8, total: 19 },
    downSpeed: "0 B/s",
    upSpeed: "0 B/s",
    ratio: 0.88,
    uploaded: "890 MB",
    downloaded: "3.4 GB",
    remaining: "216 MB",
    wasted: "0 B",
    tracker: "https://manjaro.org/announce",
    trackerUpdate: "5 min ago",
    lastActive: "now",
    maxPeers: 45,
    downLimit: "Unlimited",
    upLimit: "Unlimited",
    error: null,
    addedAt: "2026-07-04T20:15:00Z",
    trackers: [
      {
        id: "tr-manjaro",
        url: "https://manjaro.org/announce",
        status: "working",
        lastAnnounce: "5 min ago",
        seeders: 31,
        leechers: 19,
      },
    ],
    peersList: [],
    files: isoFiles("manjaro-kde-24.2.1-240726-linux612", "3.6 GB"),
  },
  {
    id: "t-linuxmint",
    name: "linuxmint-22.1-cinnamon-64bit.iso",
    size: "2.8 GB",
    sizeBytes: 2_800_000_000,
    progress: 1,
    status: "stopped",
    seeds: { connected: 0, total: 0 },
    peers: { connected: 0, total: 0 },
    downSpeed: "0 B/s",
    upSpeed: "0 B/s",
    ratio: 1.0,
    uploaded: "2.8 GB",
    downloaded: "2.8 GB",
    remaining: "0 B",
    wasted: "0 B",
    tracker: "http://linuxmint.com/announce.php",
    trackerUpdate: "2 d ago",
    lastActive: "2 d ago",
    maxPeers: 50,
    downLimit: "Unlimited",
    upLimit: "Unlimited",
    error: null,
    addedAt: "2026-06-20T08:30:00Z",
    trackers: [
      {
        id: "tr-mint",
        url: "http://linuxmint.com/announce.php",
        status: "working",
        lastAnnounce: "2 d ago",
        seeders: 0,
        leechers: 0,
      },
    ],
    peersList: [],
    files: isoFiles("linuxmint-22.1-cinnamon-64bit", "2.8 GB"),
  },
  {
    id: "t-alpine",
    name: "alpine-standard-3.21.3-x86_64.iso",
    size: "268 MB",
    sizeBytes: 268_000_000,
    progress: 0.42,
    status: "error",
    seeds: { connected: 0, total: 9 },
    peers: { connected: 1, total: 3 },
    downSpeed: "0 B/s",
    upSpeed: "0 B/s",
    ratio: 0.12,
    uploaded: "32 KB",
    downloaded: "112 MB",
    remaining: "156 MB",
    wasted: "4.2 MB",
    tracker: "udp://tracker.opentrackr.org:1337/announce",
    trackerUpdate: "12 min ago",
    lastActive: "18 min ago",
    maxPeers: 30,
    downLimit: "Unlimited",
    upLimit: "Unlimited",
    error: "Tracker returned error: unregistered torrent",
    addedAt: "2026-07-03T17:55:00Z",
    trackers: [
      {
        id: "tr-opentrackr",
        url: "udp://tracker.opentrackr.org:1337/announce",
        status: "error",
        lastAnnounce: "12 min ago",
        seeders: 9,
        leechers: 3,
      },
    ],
    peersList: [],
    files: isoFiles("alpine-standard-3.21.3-x86_64", "268 MB"),
  },
];

export const CATEGORY_LABELS: Record<CategoryFilter["id"], string> = {
  all: "All",
  downloading: "Downloading",
  completed: "Completed",
  active: "Active",
  inactive: "Inactive",
  stopped: "Stopped",
  error: "Error",
};

export function buildCategoryFilters(torrents: TorrentItem[]): CategoryFilter[] {
  const counts: Record<CategoryFilter["id"], number> = {
    all: torrents.length,
    downloading: 0,
    completed: 0,
    active: 0,
    inactive: 0,
    stopped: 0,
    error: 0,
  };

  for (const torrent of torrents) {
    if (torrent.status === "downloading" || torrent.status === "checking") counts.downloading += 1;
    if (torrent.progress >= 1 || torrent.status === "seeding") counts.completed += 1;
    if (torrent.status === "downloading" || torrent.status === "seeding" || torrent.status === "checking")
      counts.active += 1;
    if (torrent.status === "paused") counts.inactive += 1;
    if (torrent.status === "stopped") counts.stopped += 1;
    if (torrent.status === "error") counts.error += 1;
  }

  return (Object.keys(CATEGORY_LABELS) as CategoryFilter["id"][]).map((id) => ({
    id,
    label: CATEGORY_LABELS[id],
    count: counts[id],
  }));
}

export function buildTrackerGroups(torrents: TorrentItem[]): TrackerGroup[] {
  const map = new Map<string, TrackerGroup>();
  for (const torrent of torrents) {
    const existing = map.get(torrent.tracker);
    if (existing) {
      existing.count += 1;
    } else {
      map.set(torrent.tracker, { id: torrent.tracker, url: torrent.tracker, count: 1 });
    }
  }
  return [...map.values()].sort((a, b) => a.url.localeCompare(b.url));
}
