#!/bin/sh

# Remove all but last few runtimes
cd /home/ubuntu/fathom/runtimes
rm -rf `ls -r | tail -n +5`

# Clone new runtime
EPOCH="$(eval date +%s)"
git clone https://[AUTH_KEY]:x-oauth-basic@github.com/fathom/fathom-engine-api.git /home/ubuntu/fathom/runtimes/$EPOCH --quiet
cd /home/ubuntu/fathom/runtimes/$EPOCH
git checkout production

# Copy env vars
cp /home/ubuntu/fathom/config.ini /home/ubuntu/fathom/runtimes/$EPOCH/src/config.ini
cd /home/ubuntu/fathom/runtimes/$EPOCH

# Install requirements
pip3 install -r src/requirements.txt --quiet
pip install typing_extensions==4.7.1 --upgrade

# Bundle install so we can run our ruby script to determine which branch to checkout
sh production_start

# Sleep to avoid thrashing on error
sleep 10
