/**
 * Stub data for the Memory workspace — adapted from Longformer Psyche demo.
 * Phase 1 replaces this with GET /api/memory/* responses.
 */
import type { MemoryWorkspaceData } from "./types";
import {
  ETHICAL_PRINCIPLES,
  ETHICS_DOCUMENT_V2,
  INTEGRAL_MAP_DOCUMENT,
  WORLDVIEW_DOCUMENT,
  WORLD_MODEL_EDGES,
  WORLD_MODEL_NODES,
} from "./worldModelData";
import {
  Bookmark,
  Brain,
  Compass,
  Database,
  FileText,
  GitBranch,
  Globe,
  LayoutDashboard,
  Map,
  ScrollText,
  Settings,
  Sparkles,
} from "lucide-react";

export const MEMORY_WORKSPACE_MOCK: MemoryWorkspaceData = {
  productName: "Memory",
  modelName: "Arco",
  tagline: "Typed memory, vector stores, and agent permissions",
  navItems: [
    { id: "dashboard", label: "Dashboard", icon: LayoutDashboard, view: "dashboard", section: "overview" },
    { id: "memory", label: "Memory", icon: Bookmark, view: "memory", section: "stores" },
    { id: "knowledge-graph", label: "Knowledge Graph", icon: GitBranch, view: "knowledge-graph", section: "stores" },
    { id: "rag", label: "RAG Pipeline", icon: Sparkles, view: "rag", section: "stores" },
    { id: "vector-db", label: "Vector Database", icon: Database, view: "vector-db", section: "stores" },
    { id: "world-model", label: "World Model", icon: Compass, view: "world-model", section: "identity" },
    { id: "worldview-md", label: "Worldview.md", icon: Globe, view: "worldview-md", section: "identity" },
    { id: "integral-map-md", label: "Integral Map.md", icon: Map, view: "integral-map-md", section: "identity" },
    { id: "soul-md", label: "Soul.md", icon: Brain, view: "soul-md", section: "identity" },
    { id: "ethics-md", label: "Ethics.md", icon: ScrollText, view: "ethics-md", section: "identity" },
    { id: "user-md", label: "User.md", icon: FileText, view: "user-md", section: "identity" },
    { id: "settings", label: "Settings", icon: Settings, view: "settings", section: "identity" },
  ],
  overviewMetrics: [
    { id: "memories", label: "Memory entries", value: "847", tone: "accent", change: "+23 this week" },
    { id: "graph-nodes", label: "Graph nodes", value: "1,204", tone: "neutral", change: "142 new entities" },
    { id: "rag-queries", label: "RAG queries (24h)", value: "312", tone: "success", change: "94% grounded" },
    { id: "vector-health", label: "Vector index health", value: "98.2%", tone: "success", change: "All collections synced" },
  ],
  memoryEntries: [
    {
      id: "mem-1",
      kind: "semantic",
      collectionId: "semantic:personal",
      title: "User prefers concise technical explanations",
      summary:
        "Consistently asks for direct answers with code examples. Avoids lengthy preamble and marketing language.",
      status: "active",
      source: "conversation-analysis",
      confidence: 94,
      tags: ["preference", "communication", "user-profile"],
      lastAccessedAt: "2026-07-06T12:00:00.000Z",
      createdAt: "2026-06-01T10:00:00.000Z",
      updatedAt: "2026-07-06T12:00:00.000Z",
    },
    {
      id: "mem-2",
      kind: "episodic",
      collectionId: "episodic:sessions",
      title: "Debugging session: NavRail reorder hook",
      summary: "Fixed drag-and-drop state persistence in useNavRailReorder during workspace pin customization.",
      status: "active",
      source: "session-2026-07-01",
      confidence: 88,
      tags: ["debugging", "nav-rail", "react-hooks"],
      sourceSessionId: "sess-demo-1",
      lastAccessedAt: "2026-07-05T18:00:00.000Z",
      createdAt: "2026-07-01T16:00:00.000Z",
      updatedAt: "2026-07-05T18:00:00.000Z",
    },
    {
      id: "mem-3",
      kind: "working",
      collectionId: "working:session",
      title: "Active task: Memory v1 spec and UI stub",
      summary: "Implementing os.memory@1 types, Memory app shell, and Settings placeholders before server kernel.",
      status: "active",
      source: "current-session",
      confidence: 99,
      tags: ["context", "memory", "phase-0"],
      lastAccessedAt: "2026-07-06T22:00:00.000Z",
      createdAt: "2026-07-06T20:00:00.000Z",
      updatedAt: "2026-07-06T22:00:00.000Z",
    },
    {
      id: "mem-4",
      kind: "procedural",
      collectionId: "procedural:workflows",
      title: "Code review pattern: minimal diffs",
      summary: "Prefer focused changes without over-engineering. Reuse existing components before new abstractions.",
      status: "active",
      source: "feedback-loop",
      confidence: 91,
      tags: ["workflow", "code-style"],
      lastAccessedAt: "2026-07-03T09:00:00.000Z",
      createdAt: "2026-05-15T09:00:00.000Z",
      updatedAt: "2026-07-03T09:00:00.000Z",
    },
    {
      id: "mem-5",
      kind: "semantic",
      collectionId: "semantic:personal",
      title: "Conflicting memory: default pinned apps",
      summary: "Two versions of dock pin order detected after layout migration. Needs reconciliation.",
      status: "conflicted",
      source: "memory-sync",
      confidence: 62,
      tags: ["conflict", "dock", "layout"],
      lastAccessedAt: "2026-07-06T17:00:00.000Z",
      createdAt: "2026-07-06T16:00:00.000Z",
      updatedAt: "2026-07-06T17:00:00.000Z",
    },
    {
      id: "mem-6",
      kind: "episodic",
      collectionId: "episodic:sessions",
      title: "Shipped agent extensibility Phases A–E",
      summary: "Tool registry, MCP client, skills, ACP, and outward MCP all landed in the agent loop.",
      status: "archived",
      source: "deployment-log",
      confidence: 96,
      tags: ["shipping", "agent", "mcp"],
      lastAccessedAt: "2026-07-05T08:00:00.000Z",
      createdAt: "2026-07-05T08:00:00.000Z",
      updatedAt: "2026-07-05T08:00:00.000Z",
    },
  ],
  graphNodes: [
    { id: "n-user", label: "User", type: "entity", connections: 8 },
    { id: "n-arco", label: "Arco", type: "entity", connections: 12 },
    { id: "n-memory", label: "Memory System", type: "concept", connections: 9 },
    { id: "n-rag", label: "RAG Pipeline", type: "concept", connections: 7 },
    { id: "n-vector", label: "Vector Store", type: "concept", connections: 6 },
  ],
  graphEdges: [
    { id: "e1", fromId: "n-user", toId: "n-arco", relation: "related", weight: 0.9 },
    { id: "e2", fromId: "n-arco", toId: "n-memory", relation: "mentions", weight: 0.8 },
    { id: "e3", fromId: "n-memory", toId: "n-rag", relation: "supports", weight: 0.7 },
    { id: "e4", fromId: "n-rag", toId: "n-vector", relation: "derived_from", weight: 0.85 },
    { id: "e5", fromId: "n-vector", toId: "n-memory", relation: "supports", weight: 0.65 },
  ],
  ragQueries: [
    {
      id: "q1",
      query: "What are the user's preferences for code changes and workspace design?",
      timestamp: "Today, 2:14 PM",
      latencyMs: 142,
      chunksRetrieved: 5,
      answerPreview: "User prefers minimal diffs, Arco design tokens, and stub-before-wire UI migrations.",
    },
    {
      id: "q2",
      query: "Recent debugging context for navigation components",
      timestamp: "Yesterday, 4:02 PM",
      latencyMs: 98,
      chunksRetrieved: 3,
      answerPreview: "NavRail reorder hook fix; drag state persisted via normalized pinned id list.",
    },
  ],
  ragChunks: [
    {
      id: "c1",
      source: "reference:docs/memory-plan.md",
      content: "Recall is budgeted. Prefill injected before a turn is capped (tokens + item count).",
      score: 0.92,
      tokens: 18,
    },
    {
      id: "c2",
      source: "semantic:personal/mem-1",
      content: "User prefers concise technical explanations with code examples.",
      score: 0.88,
      tokens: 12,
    },
  ],
  collections: [
    {
      id: "reference:notes",
      kind: "reference",
      name: "Notes corpus",
      description: "Ingested markdown from the Notes workspace",
      embedderId: "local-nomic",
      backendId: "local-sqlite-vec",
      vectorCount: 12400,
      entryCount: 890,
      dimensions: 768,
      health: "healthy",
      lastIndexed: "2026-07-06T10:00:00.000Z",
      retentionDays: null,
      createdAt: "2026-06-01T00:00:00.000Z",
      updatedAt: "2026-07-06T10:00:00.000Z",
    },
    {
      id: "semantic:personal",
      kind: "semantic",
      name: "Personal facts",
      embedderId: "local-nomic",
      backendId: "local-sqlite-vec",
      vectorCount: 412,
      entryCount: 412,
      dimensions: 768,
      health: "healthy",
      lastIndexed: "2026-07-06T08:00:00.000Z",
      retentionDays: null,
      createdAt: "2026-06-01T00:00:00.000Z",
      updatedAt: "2026-07-06T08:00:00.000Z",
    },
    {
      id: "episodic:sessions",
      kind: "episodic",
      name: "Session summaries",
      embedderId: "local-nomic",
      backendId: "local-sqlite-vec",
      vectorCount: 847,
      entryCount: 847,
      dimensions: 768,
      health: "syncing",
      lastIndexed: "2026-07-06T22:30:00.000Z",
      retentionDays: 365,
      createdAt: "2026-06-01T00:00:00.000Z",
      updatedAt: "2026-07-06T22:30:00.000Z",
    },
  ],
  backends: [
    {
      id: "local-sqlite-vec",
      label: "SQLite + sqlite-vec",
      kind: "embedded",
      status: "available",
      description: "Default embedded vector index under data/memory/",
    },
    {
      id: "qdrant-local",
      label: "Qdrant (local HTTP)",
      kind: "http",
      status: "unconfigured",
      description: "Optional sidecar — configure URL in Settings → Memory",
    },
  ],
  embedders: [
    { id: "local-nomic", label: "Nomic Embed (local)", dimensions: 768, status: "available" },
    {
      id: "openai-text-3-small",
      label: "OpenAI text-embedding-3-small",
      dimensions: 1536,
      status: "error",
    },
  ],
  grants: [
    { principalId: "agent:builtin", scope: { level: "kind", kind: "semantic" }, access: "write" },
    { principalId: "agent:builtin", scope: { level: "kind", kind: "episodic" }, access: "write" },
    { principalId: "agent:acp:claude-code", scope: { level: "kind", kind: "semantic" }, access: "read" },
    { principalId: "agent:automation:*", scope: { level: "kind", kind: "reference" }, access: "read" },
  ],
  soulDocument: {
    id: "identity:soul",
    title: "Soul",
    filename: "SOUL.md",
    version: "1.2",
    lastEdited: "2026-07-01",
    sections: [
      {
        id: "s1",
        heading: "Core disposition",
        content: "Arco is concise, capable, and acts immediately. It builds before it narrates.",
      },
      {
        id: "s2",
        heading: "Boundaries",
        content: "Never exfiltrate secrets. Confirm destructive actions. Respect memory grants.",
      },
    ],
  },
  worldviewDocument: WORLDVIEW_DOCUMENT,
  integralMapDocument: INTEGRAL_MAP_DOCUMENT,
  ethicsDocument: ETHICS_DOCUMENT_V2,
  userDocument: {
    id: "identity:user",
    title: "User",
    filename: "USER.md",
    version: "1.1",
    lastEdited: "2026-07-04",
    sections: [
      {
        id: "u1",
        heading: "Working style",
        content: "Prefers staged delivery with commits between phases. Uses Arco as a generative OS shell.",
      },
    ],
  },
  ethicalPrinciples: ETHICAL_PRINCIPLES,
  worldModelNodes: WORLD_MODEL_NODES,
  worldModelEdges: WORLD_MODEL_EDGES,
  systemNote: "Phase 0.5 prototype — world model explorer + identity seeds. Wire to /api/memory in Phase 1.",
};
