import type { ApiIntegration } from "./types";

export const APIS_MOCK: ApiIntegration[] = [
  {
    id: "api-github",
    name: "GitHub",
    description: "Issues, pull requests, checks, and repository operations from the workspace.",
    author: "GitHub",
    version: "2.1.0",
    installed: true,
    icon: "wrench",
    category: "Development",
    rating: 4.9,
    docsUrl: "https://docs.github.com/en/rest",
  },
  {
    id: "api-linear",
    name: "Linear",
    description: "Sync issues, cycles, and project updates with your Linear workspace.",
    author: "Linear",
    version: "0.9.3",
    installed: true,
    icon: "target",
    category: "Project Management",
    rating: 4.7,
  },
  {
    id: "api-notion",
    name: "Notion",
    description: "Read and write pages, databases, and blocks in your Notion workspace.",
    author: "Notion",
    version: "1.0.8",
    installed: true,
    icon: "sticky-note",
    category: "Knowledge",
    rating: 4.6,
  },
  {
    id: "api-figma",
    name: "Figma",
    description: "Read designs, screenshots, and variables from Figma files via MCP.",
    author: "Figma",
    version: "1.4.2",
    installed: true,
    icon: "palette",
    category: "Design",
    rating: 4.8,
  },
  {
    id: "api-slack",
    name: "Slack",
    description: "Send messages, read channels, and trigger workflows from Slack.",
    author: "Slack",
    version: "1.2.1",
    installed: false,
    icon: "users",
    category: "Communication",
    rating: 4.5,
  },
  {
    id: "api-datadog",
    name: "Datadog",
    description: "Query metrics, logs, and monitors for production observability.",
    author: "Datadog",
    version: "0.6.0",
    installed: false,
    icon: "bar-chart-3",
    category: "Observability",
    rating: 4.4,
  },
  {
    id: "api-postgres",
    name: "PostgreSQL",
    description: "Run read-only SQL queries against connected database instances.",
    author: "Community",
    version: "0.2.0",
    installed: false,
    icon: "table",
    category: "Data",
    rating: 4.2,
  },
  {
    id: "api-browser",
    name: "Browser Automation",
    description: "Navigate, snapshot, and interact with web pages for testing and scraping.",
    author: "Arco",
    version: "0.3.5",
    installed: true,
    icon: "search",
    category: "Automation",
    rating: 4.3,
  },
  {
    id: "api-stripe",
    name: "Stripe",
    description: "Customers, subscriptions, invoices, and payment intents.",
    author: "Stripe",
    version: "1.0.0",
    installed: false,
    icon: "wallet",
    category: "Finance",
    rating: 4.6,
  },
  {
    id: "api-openweather",
    name: "OpenWeather",
    description: "Current conditions and forecasts for location-aware automations.",
    author: "OpenWeather",
    version: "0.1.4",
    installed: false,
    icon: "cloud-sun",
    category: "Data",
    rating: 4.1,
  },
];
