/**
 * Seed agent profiles — aggregates built-in runtime, ACP presets, automations,
 * and channel bots into one registry for the Agents manager UI (Phase 0 stub).
 */
import type { AgentProfile } from "./types";

export const AGENTS_MOCK: AgentProfile[] = [
  {
    id: "agent:builtin",
    name: "Arco",
    tagline: "Default assistant for Chat and Studio",
    description:
      "The built-in agent loop with tool calling, skills, and OS integration. Uses the agent.chat model slot and your configured tool policy.",
    principalId: "agent:builtin",
    runtime: "builtin",
    status: "active",
    enabled: true,
    avatar: { kind: "emoji", value: "✦", color: "accent" },
    source: "seed",
    modelSlot: "agent.chat",
    approvedModels: ["openai.gpt-5.5", "anthropic.claude-sonnet-4", "google.gemini-2.5-pro"],
    defaultModel: "openai.gpt-5.5",
    memoryPrincipalId: "agent:builtin",
    memoryGrants: [
      { kind: "read", scope: "user:*", description: "Read user memory entries" },
      { kind: "write", scope: "agent:builtin", description: "Write to agent-scoped memory" },
    ],
    memoryEntryCount: 142,
    documents: [
      {
        id: "soul",
        name: "Soul",
        path: "memory/soul.md",
        description: "Core personality and values",
        preview: "# Soul\n\nCurious, direct, and tool-forward. Prefer showing work over describing it.",
      },
      {
        id: "instructions",
        name: "Instructions",
        path: "agents/builtin/instructions.md",
        description: "Runtime behavior and tool usage norms",
      },
    ],
    toolCount: 24,
    policyLevel: "balanced",
    skillGates: ["arco-ui-migration", "literate-pbrt"],
    mcpServers: ["figma", "kosmographica"],
    labels: ["certified", "standard safety"],
    safetyLevel: "standard",
  },
  {
    id: "agent:acp:claude-code",
    name: "Claude Code",
    tagline: "ACP — Anthropic coding agent",
    description:
      "External ACP runtime for deep codebase work. Spawns a separate process with elevated tool access; confirm on exec by default.",
    principalId: "agent:acp:claude-code",
    runtime: "acp",
    acpPresetId: "claude-code",
    status: "idle",
    enabled: true,
    avatar: { kind: "emoji", value: "⌘", color: "violet" },
    source: "seed",
    modelSlot: "agent.chat",
    approvedModels: ["anthropic.claude-sonnet-4", "anthropic.claude-opus-4"],
    defaultModel: "anthropic.claude-sonnet-4",
    memoryPrincipalId: "agent:acp:claude-code",
    memoryGrants: [
      { kind: "read", scope: "workspace:*", description: "Read project context" },
      { kind: "write", scope: "agent:acp:claude-code", description: "Agent-scoped notes" },
    ],
    memoryEntryCount: 38,
    documents: [
      {
        id: "acp-instructions",
        name: "ACP Instructions",
        path: "agents/acp/claude-code.md",
        description: "Spawn command and session defaults",
      },
    ],
    toolCount: 18,
    policyLevel: "permissive",
    skillGates: [],
    mcpServers: ["figma"],
    labels: ["elevated", "18+"],
    safetyLevel: "elevated",
  },
  {
    id: "agent:acp:codex",
    name: "Codex",
    tagline: "ACP — OpenAI coding agent",
    description: "OpenAI Codex via ACP for fast iteration on scripts and small patches.",
    principalId: "agent:acp:codex",
    runtime: "acp",
    acpPresetId: "codex",
    status: "offline",
    enabled: false,
    avatar: { kind: "emoji", value: "◇", color: "teal" },
    source: "seed",
    approvedModels: ["openai.gpt-5.5", "openai.o4-mini"],
    defaultModel: "openai.gpt-5.5",
    memoryPrincipalId: "agent:acp:codex",
    memoryGrants: [{ kind: "read", scope: "workspace:*" }],
    memoryEntryCount: 0,
    documents: [],
    toolCount: 12,
    policyLevel: "balanced",
    skillGates: [],
    mcpServers: [],
    labels: ["partial"],
    safetyLevel: "standard",
  },
  {
    id: "agent:cursor",
    name: "Cursor",
    tagline: "Cloud agent via Cursor API",
    description: "Routes chat turns to Cursor's cloud agent when configured with an API key.",
    principalId: "agent:cursor",
    runtime: "cursor",
    status: "idle",
    enabled: true,
    avatar: { kind: "emoji", value: "▶", color: "blue" },
    source: "seed",
    approvedModels: ["cursor.auto"],
    defaultModel: "cursor.auto",
    memoryPrincipalId: "agent:cursor",
    memoryGrants: [],
    memoryEntryCount: 0,
    documents: [],
    toolCount: 0,
    policyLevel: "conservative",
    skillGates: [],
    mcpServers: [],
    labels: ["external runtime"],
    safetyLevel: "standard",
  },
  {
    id: "agent:automation:morning-brief",
    name: "Morning Brief",
    tagline: "Scheduled automation — weekdays 9am",
    description:
      "Headless agent that summarizes calendar and tasks. Narrow tool grants; deny tools that need confirmation.",
    principalId: "agent:automation:morning-brief",
    runtime: "automation",
    status: "idle",
    enabled: true,
    avatar: { kind: "emoji", value: "☀", color: "amber" },
    source: "automation",
    approvedModels: ["openai.gpt-5.5-mini"],
    defaultModel: "openai.gpt-5.5-mini",
    memoryPrincipalId: "agent:automation:morning-brief",
    memoryGrants: [
      { kind: "read", scope: "calendar:*" },
      { kind: "read", scope: "tasks:*" },
    ],
    memoryEntryCount: 12,
    documents: [
      {
        id: "prompt",
        name: "Prompt",
        path: "automations/morning-brief/prompt.md",
        preview: "Summarize today's calendar and open tasks in a concise morning brief.",
      },
    ],
    toolCount: 6,
    policyLevel: "conservative",
    skillGates: [],
    mcpServers: [],
    labels: ["automation", "restricted context"],
    safetyLevel: "restricted",
  },
  {
    id: "agent:channel:telegram",
    name: "Telegram Bot",
    tagline: "Channel agent — DM replies",
    description: "Inbound channel bot with read-only memory and no exec tools.",
    principalId: "agent:channel:telegram",
    runtime: "channel",
    status: "running",
    enabled: true,
    avatar: { kind: "emoji", value: "✉", color: "green" },
    source: "channel",
    approvedModels: ["openai.gpt-5.5-mini", "google.gemini-2.5-flash"],
    defaultModel: "openai.gpt-5.5-mini",
    memoryPrincipalId: "agent:channel:telegram",
    memoryGrants: [{ kind: "read", scope: "channel:telegram:*" }],
    memoryEntryCount: 89,
    documents: [
      {
        id: "channel-persona",
        name: "Channel Persona",
        path: "channels/telegram/persona.md",
        description: "Tone and boundaries for DM replies",
      },
    ],
    toolCount: 4,
    policyLevel: "conservative",
    skillGates: [],
    mcpServers: [],
    labels: ["channel", "restricted"],
    safetyLevel: "restricted",
  },
  {
    id: "agent:user:research",
    name: "Research Scout",
    tagline: "Custom — web research and synthesis",
    description: "User-created agent with browser tools and RAG memory access for long-form research.",
    principalId: "agent:user:research",
    runtime: "builtin",
    status: "idle",
    enabled: true,
    avatar: { kind: "emoji", value: "🔭", color: "indigo" },
    source: "user",
    modelSlot: "agent.chat",
    approvedModels: [
      "openai.gpt-5.5",
      "anthropic.claude-sonnet-4",
      "google.gemini-2.5-pro",
      "perplexity.sonar",
    ],
    defaultModel: "perplexity.sonar",
    memoryPrincipalId: "agent:user:research",
    memoryGrants: [
      { kind: "read", scope: "rag:*" },
      { kind: "write", scope: "agent:user:research" },
    ],
    memoryEntryCount: 256,
    documents: [
      {
        id: "research-brief",
        name: "Research Brief",
        path: "agents/research/brief.md",
        description: "How to structure findings and cite sources",
      },
      {
        id: "output-format",
        name: "Output Format",
        path: "agents/research/output.md",
      },
    ],
    toolCount: 14,
    policyLevel: "balanced",
    skillGates: ["canvas"],
    mcpServers: ["kosmographica"],
    labels: ["custom"],
    safetyLevel: "standard",
  },
  {
    id: "agent:user:reviewer",
    name: "Code Reviewer",
    tagline: "Custom — PR and diff review",
    description: "Focused reviewer agent with git read tools and a strict review checklist document set.",
    principalId: "agent:user:reviewer",
    runtime: "builtin",
    status: "offline",
    enabled: false,
    avatar: { kind: "initials", value: "CR", color: "rose" },
    source: "user",
    approvedModels: ["anthropic.claude-sonnet-4", "openai.gpt-5.5"],
    defaultModel: "anthropic.claude-sonnet-4",
    memoryPrincipalId: "agent:user:reviewer",
    memoryGrants: [{ kind: "read", scope: "git:*" }],
    memoryEntryCount: 17,
    documents: [
      {
        id: "checklist",
        name: "Review Checklist",
        path: "agents/reviewer/checklist.md",
        preview: "## Review checklist\n\n- Security implications\n- Test coverage\n- API compatibility",
      },
    ],
    toolCount: 8,
    policyLevel: "conservative",
    skillGates: ["babysit"],
    mcpServers: [],
    labels: ["custom", "disabled"],
    safetyLevel: "standard",
  },
];
