#!/bin/bash

# $1: command line parameter => 'whisper' or 'heartbeat'
process=$1

cd src
cp config_$process.ini config.ini
if [ $process == "heartbeat" ] ; then
python3 heartbeat.py
fi
if [ $process == "whisper" ] ; then
python3 start.py
fi
