{
  explore {
    internalId
    title
    primary
    podcasts {
      info {
        guid
        urlSlug
        title
        heroImageUrl
        colors
        nameId
        description
        categories
      }
    }
  }
}
