query($purchaseGuid: String!) {
  podiumGetPodiumPurchase(purchaseGuid: $purchaseGuid) {
    completed,
    quantity,
    productTitle,
    productDescription,
    productType,
    productCredits,
    productPeriod,
    productPrice
  }
}