import type { KeyEntry } from "./types";

export const KEY_WALLET_MOCK: KeyEntry[] = [
  {
    id: "anthropic",
    name: "Anthropic API key",
    envName: "ANTHROPIC_API_KEY",
    scope: "llm",
    usedBy: "Model provider · Agent",
    maskedValue: "••••7kQp",
    updatedAt: "2026-07-01T14:22:00.000Z",
    description: "Primary frontier model for chat, Studio, and automations.",
  },
  {
    id: "openai",
    name: "OpenAI API key",
    envName: "OPENAI_API_KEY",
    scope: "llm",
    usedBy: "Model provider · Voice brain",
    maskedValue: "••••9xLm",
    updatedAt: "2026-06-18T09:10:00.000Z",
  },
  {
    id: "github-mcp",
    name: "GitHub token",
    envName: "GITHUB_PERSONAL_ACCESS_TOKEN",
    scope: "mcp",
    usedBy: "MCP: GitHub",
    maskedValue: "••••ghp_",
    updatedAt: "2026-06-25T16:40:00.000Z",
    description: "Issues, pull requests, and repository operations.",
  },
  {
    id: "linear-mcp",
    name: "Linear API key",
    envName: "LINEAR_API_KEY",
    scope: "mcp",
    usedBy: "MCP: Linear",
    maskedValue: "••••lin_",
    updatedAt: "2026-06-20T11:05:00.000Z",
  },
  {
    id: "telegram",
    name: "Telegram bot token",
    envName: "TELEGRAM_BOT_TOKEN",
    scope: "channel",
    usedBy: "Channel: Telegram",
    maskedValue: "••••8421",
    updatedAt: "2026-06-12T08:30:00.000Z",
  },
  {
    id: "external-mcp",
    name: "External MCP bearer",
    envName: "ARCO_EXTERNAL_MCP_TOKEN",
    scope: "external",
    usedBy: "External access · Outward MCP",
    maskedValue: "••••ext9",
    updatedAt: "2026-06-28T19:15:00.000Z",
    description: "Scoped token for third-party clients calling Arco's MCP endpoint.",
  },
  {
    id: "replicate",
    name: "Replicate API token",
    envName: "REPLICATE_API_TOKEN",
    scope: "model",
    usedBy: "Models · Image generation",
    maskedValue: "••••r8_",
    updatedAt: "2026-07-03T10:00:00.000Z",
  },
  {
    id: "claude-acp",
    name: "Claude Code subscription",
    envName: "ANTHROPIC_API_KEY",
    scope: "acp",
    usedBy: "ACP: Claude Code",
    maskedValue: "••••(host)",
    updatedAt: "2026-07-05T12:00:00.000Z",
    description: "Host subscription login takes priority over saved keys for ACP agents.",
  },
];
