/**
 * Shared deploy/ops primitives — used by builtin agent tools and the
 * kosmos-ops MCP server so Codex, Claude, Gemini, and the native loop
 * all get the same folder / Docker / Coolify capabilities.
 */
import { execFile } from "node:child_process";
import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import { dataDirs } from "../env.js";
import { getActiveRoot } from "../stores/projectStore.js";

const execFileAsync = promisify(execFile);

export interface OpsConfig {
  enabled: boolean;
  coolifyAppsDir: string | null;
  dockerAvailable: boolean;
  workspaceRoot: string;
}

export function getOpsConfig(): OpsConfig {
  const coolifyAppsDir = process.env.ARCO_COOLIFY_APPS_DIR?.trim() || null;
  return {
    enabled: process.env.ARCO_OPS_ENABLED === "1" || Boolean(coolifyAppsDir),
    coolifyAppsDir,
    dockerAvailable: fs.existsSync("/var/run/docker.sock"),
    workspaceRoot: getActiveRoot(),
  };
}

function slugify(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 48) || "app"
  );
}

function resolveTargetDir(target: string, base: "workspace" | "coolify" | "auto"): string {
  const cfg = getOpsConfig();
  if (path.isAbsolute(target)) return path.resolve(target);

  if (base === "coolify") {
    if (!cfg.coolifyAppsDir) {
      throw new Error(
        "Coolify apps directory is not mounted. Set ARCO_COOLIFY_APPS_DIR on the host/container.",
      );
    }
    return path.resolve(cfg.coolifyAppsDir, target);
  }

  if (base === "auto" && cfg.coolifyAppsDir && target.startsWith("coolify/")) {
    return path.resolve(cfg.coolifyAppsDir, target.slice("coolify/".length));
  }

  return path.resolve(getActiveRoot(), target);
}

export async function createDirectory(input: {
  path: string;
  base?: "workspace" | "coolify" | "auto";
}): Promise<{ path: string; created: boolean }> {
  const abs = resolveTargetDir(input.path, input.base ?? "auto");
  const existed = fs.existsSync(abs);
  await fsp.mkdir(abs, { recursive: true });
  return { path: abs, created: !existed };
}

export async function dockerBuild(input: {
  context: string;
  tag: string;
  dockerfile?: string;
}): Promise<{ tag: string; stdout: string; stderr: string }> {
  const cfg = getOpsConfig();
  if (!cfg.dockerAvailable) {
    throw new Error("Docker socket is not available. Mount /var/run/docker.sock to enable builds.");
  }
  const context = path.isAbsolute(input.context)
    ? input.context
    : path.resolve(getActiveRoot(), input.context);
  if (!fs.existsSync(context)) throw new Error(`Build context not found: ${context}`);

  const args = ["build", "-t", input.tag];
  if (input.dockerfile) args.push("-f", input.dockerfile);
  args.push(context);

  const { stdout, stderr } = await execFileAsync("docker", args, {
    timeout: 600_000,
    maxBuffer: 10 * 1024 * 1024,
  });
  return { tag: input.tag, stdout: stdout.slice(-4000), stderr: stderr.slice(-2000) };
}

const COOLIFY_COMPOSE = `# Generated by Kosmos Ops — Coolify-managed service
services:
  app:
    image: {{IMAGE}}
    restart: unless-stopped
    expose:
      - "{{PORT}}"
    networks:
      coolify:
        aliases:
          - {{SLUG}}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:{{PORT}}/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  coolify:
    external: true
    name: coolify
`;

export async function coolifyCreateApp(input: {
  name: string;
  image?: string;
  port?: number;
  domain?: string;
  template?: "static" | "node";
}): Promise<{
  slug: string;
  dir: string;
  composePath: string;
  dockerfilePath?: string;
}> {
  const cfg = getOpsConfig();
  if (!cfg.coolifyAppsDir) {
    throw new Error(
      "Coolify apps directory is not mounted. Set ARCO_COOLIFY_APPS_DIR (e.g. /host-coolify/applications).",
    );
  }

  const slug = slugify(input.name);
  const dir = path.join(cfg.coolifyAppsDir, slug);
  await fsp.mkdir(dir, { recursive: true });

  const template = input.template ?? "static";
  const port = input.port ?? (template === "static" ? 80 : 8080);
  const image = input.image ?? `${slug}:latest`;

  let dockerfilePath: string | undefined;
  if (template === "static") {
    dockerfilePath = path.join(dir, "Dockerfile");
    await fsp.writeFile(
      dockerfilePath,
      `FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80
`,
    );
    await fsp.writeFile(
      path.join(dir, "index.html"),
      `<!doctype html><html><head><meta charset="utf-8"><title>${input.name}</title></head><body><h1>${input.name}</h1></body></html>\n`,
    );
  } else {
    dockerfilePath = path.join(dir, "Dockerfile");
    await fsp.writeFile(
      dockerfilePath,
      `FROM node:22-bookworm-slim
WORKDIR /app
COPY package.json ./
RUN npm install --omit=dev
COPY . .
EXPOSE ${port}
CMD ["node", "server.js"]
`,
    );
    await fsp.writeFile(
      path.join(dir, "package.json"),
      JSON.stringify({ name: slug, private: true, type: "module", scripts: { start: "node server.js" } }, null, 2),
    );
    await fsp.writeFile(
      path.join(dir, "server.js"),
      `import http from "node:http";
const port = Number(process.env.PORT || ${port});
http.createServer((_req, res) => {
  res.writeHead(200, { "content-type": "text/html" });
  res.end("<h1>${input.name}</h1>");
}).listen(port, () => console.log("listening on", port));
`,
    );
  }

  const composePath = path.join(dir, "docker-compose.yaml");
  let compose = COOLIFY_COMPOSE.replace(/\{\{IMAGE\}\}/g, image)
    .replace(/\{\{PORT\}\}/g, String(port))
    .replace(/\{\{SLUG\}\}/g, slug);

  if (input.domain) {
    compose = compose.replace(
      "    healthcheck:",
      `    labels:
      - traefik.enable=true
      - traefik.http.routers.${slug}.rule=Host(\`${input.domain}\`)
      - traefik.http.routers.${slug}.entryPoints=https
      - traefik.http.routers.${slug}.tls=true
      - traefik.http.routers.${slug}.tls.certresolver=letsencrypt
      - traefik.http.services.${slug}.loadbalancer.server.port=${port}
    healthcheck:`,
    );
  }

  await fsp.writeFile(composePath, compose);
  await fsp.writeFile(
    path.join(dir, ".env"),
    `# Kosmos-generated Coolify app\nPORT=${port}\nIMAGE=${image}\n`,
  );

  return { slug, dir, composePath, dockerfilePath };
}

export async function dockerComposeUp(input: {
  composeDir: string;
  build?: boolean;
}): Promise<{ dir: string; stdout: string; stderr: string }> {
  const cfg = getOpsConfig();
  if (!cfg.dockerAvailable) {
    throw new Error("Docker socket is not available. Mount /var/run/docker.sock to enable deploys.");
  }
  const dir = path.isAbsolute(input.composeDir)
    ? input.composeDir
    : resolveTargetDir(input.composeDir, "auto");
  if (!fs.existsSync(path.join(dir, "docker-compose.yaml"))) {
    throw new Error(`No docker-compose.yaml in ${dir}`);
  }

  const args = ["compose", "-f", "docker-compose.yaml", "up", "-d"];
  if (input.build) args.push("--build");

  let stdout = "";
  let stderr = "";
  try {
    ({ stdout, stderr } = await execFileAsync("docker", args, {
      cwd: dir,
      timeout: 600_000,
      maxBuffer: 10 * 1024 * 1024,
    }));
  } catch (err) {
    // Fallback when compose plugin is unavailable inside the container.
    const legacyArgs = ["-f", "docker-compose.yaml", "up", "-d"];
    if (input.build) legacyArgs.push("--build");
    ({ stdout, stderr } = await execFileAsync("docker-compose", legacyArgs, {
      cwd: dir,
      timeout: 600_000,
      maxBuffer: 10 * 1024 * 1024,
    }));
  }
  return { dir, stdout: stdout.slice(-4000), stderr: stderr.slice(-2000) };
}

export async function getOpsStatus(): Promise<Record<string, unknown>> {
  const cfg = getOpsConfig();
  let dockerVersion: string | null = null;
  if (cfg.dockerAvailable) {
    try {
      const { stdout } = await execFileAsync("docker", ["version", "--format", "{{.Server.Version}}"], {
        timeout: 10_000,
      });
      dockerVersion = stdout.trim() || null;
    } catch {
      dockerVersion = null;
    }
  }

  return {
    enabled: cfg.enabled,
    dockerAvailable: cfg.dockerAvailable,
    dockerVersion,
    coolifyAppsDir: cfg.coolifyAppsDir,
    workspaceRoot: cfg.workspaceRoot,
    dataDir: dataDirs.root,
    bubblewrap: fs.existsSync("/usr/bin/bwrap") ? "system" : "missing",
  };
}
