<template>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="36" height="36" style="shape-rendering: auto; display: block; background: transparent;" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle stroke-dasharray="193.20794819577225 66.40264939859075" r="41" stroke-width="8" stroke="#ffffff" fill="none" cy="50" cx="50">
  <animateTransform keyTimes="0;1" values="0 50 50;360 50 50" dur="0.7462686567164178s" repeatCount="indefinite" type="rotate" attributeName="transform"></animateTransform>
</circle><g></g></g><!-- [ldio] generated by https://loading.io --></svg>
</template>