from setuptools import setup

setup(name='fathom-core',
      version='1.0',
      description='Fathom core objects and functions',
      url='https://github.com/fathom-app/fathom-core',
      author='Fathom',
      author_email='hello@fathom.fm',
      license='',
      packages=['fathom_core'],
      install_requires=[
        'fathom-pinecone @ git+https://2c362d5f4c48f0ee727f26f7c87a7dad014242fb:x-oauth-basic@github.com/fathom-labs/fathom-pinecone.git@main#egg=fathom-pinecone',
        'timestring',
        'orator @ git+https://github.com/fathom-labs/orator@mysql-fix#egg=orator',
        'mysqlclient',
        'psycopg2',
        'boto3',
        'pymilvus==0.4.0',
        'elasticsearch==7.11.0',
        'elasticsearch-dsl==7.3.0',
        'requests',
        'spacy==2.3.1',
        'scipy',
        'numpy',
        'pandas',
        'feedparser',
        'beautifulsoup4',
        'lxml',
        'aiohttp',
        'Wand',
        'colorthief',
        'rev_ai',
        'openai==0.28.1',
        'firebase-admin',
        'deepgram-sdk==2.3.0',
        'titlecase',
        'sendgrid',
        'tenacity',
        'orjson',
        'python-dateutil',
        'redis',
        'tiktoken',
        'stripe',
        'num2words',
        'python-docx==0.8.11',
        'striprtf'
        ],
      zip_safe=False)
