version: '3.4'

services:
  app:
    build: .
    command: bash -c "npm install --silent && npm run dev"
    volumes:
      - .:/usr/src/nuxt-app
    ports:
      - "3000:3000"
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
