import type { LongformerWorkspaceData } from "./types";

export const LONGFORMER_MOCK: LongformerWorkspaceData = {
  productName: "Longformer",
  userName: "Alex Morgan",
  userEmail: "alex@meridian.dev",
  navItems: [
    { id: "library", label: "Library", view: "library" },
    { id: "in-progress", label: "In Progress", view: "in-progress", badge: "3" },
    { id: "sources", label: "Sources", view: "sources" },
    { id: "uploads", label: "Uploads", view: "uploads" },
    { id: "settings", label: "Settings", view: "settings" },
  ],
  connectedSources: [],
  pinnedTranscripts: [
    { id: "tr-001", label: "Q2 Planning — All Hands", meta: "42:18" },
    { id: "tr-002", label: "Investor Call — Series B", meta: "1:05:22" },
  ],
  processingCount: 0,
  metrics: [],
  transcripts: [
    {
      id: "tr-001",
      title: "Q2 Planning — All Hands",
      projectName: "Meridian Ops",
      sourceType: "meeting",
      sourceLabel: "Zoom",
      status: "ready",
      durationMs: 2_538_000,
      wordCount: 8420,
      speakerCount: 12,
      createdAt: "Jul 2, 2026",
      createdAtMs: Date.parse("2026-07-02T10:00:00"),
      excerpt: "…focus on shipping the mobile redesign by end of quarter…",
      language: "English",
      pinned: true,
    },
    {
      id: "tr-002",
      title: "Investor Call — Series B",
      projectName: "Meridian Ops",
      sourceType: "call",
      sourceLabel: "Phone",
      status: "ready",
      durationMs: 3_922_000,
      wordCount: 11_840,
      speakerCount: 4,
      createdAt: "Jul 1, 2026",
      createdAtMs: Date.parse("2026-07-01T14:30:00"),
      excerpt: "…runway extends through Q1 2027 with current burn rate…",
      language: "English",
      pinned: true,
    },
    {
      id: "tr-003",
      title: "Design Review — Mobile App",
      projectName: "Product",
      sourceType: "meeting",
      sourceLabel: "Google Meet",
      status: "ready",
      durationMs: 1_724_000,
      wordCount: 5620,
      speakerCount: 6,
      createdAt: "Jul 1, 2026",
      createdAtMs: Date.parse("2026-07-01T09:15:00"),
      excerpt: "…navigation pattern should follow the bottom tab bar approach…",
      language: "English",
    },
    {
      id: "tr-004",
      title: "Lenny's Podcast — Ep. 412",
      projectName: "Feeds",
      sourceType: "podcast",
      sourceLabel: "RSS Feed",
      status: "processing",
      durationMs: 5_400_000,
      createdAt: "Jul 1, 2026",
      createdAtMs: Date.parse("2026-07-01T06:00:00"),
      excerpt: "Processing speaker diarization…",
      language: "English",
    },
    {
      id: "tr-005",
      title: "Customer Interview — Acme Corp",
      projectName: "Sales",
      sourceType: "call",
      sourceLabel: "Zoom Phone",
      status: "ready",
      durationMs: 1_845_000,
      wordCount: 4890,
      speakerCount: 2,
      createdAt: "Jun 30, 2026",
      createdAtMs: Date.parse("2026-06-30T16:45:00"),
      excerpt: "…the onboarding flow lost us at the permissions step…",
      language: "English",
    },
    {
      id: "tr-006",
      title: "Voice memo — product ideas",
      projectName: "Notes",
      sourceType: "memory",
      sourceLabel: "App Memory",
      status: "ready",
      durationMs: 320_000,
      wordCount: 890,
      speakerCount: 1,
      createdAt: "Jun 30, 2026",
      createdAtMs: Date.parse("2026-06-30T11:20:00"),
      excerpt: "…transcript-to-reel pipeline for short-form clips…",
      language: "English",
    },
    {
      id: "tr-007",
      title: "Conference Talk — React Summit",
      projectName: "Events",
      sourceType: "upload",
      sourceLabel: "Manual Upload",
      status: "ready",
      durationMs: 2_700_000,
      wordCount: 7200,
      speakerCount: 1,
      createdAt: "Jun 28, 2026",
      createdAtMs: Date.parse("2026-06-28T15:30:00"),
      excerpt: "…server components changed how we think about data fetching…",
      language: "English",
    },
    {
      id: "tr-008",
      title: "Sales Call — Enterprise Lead",
      projectName: "Sales",
      sourceType: "call",
      sourceLabel: "Phone",
      status: "failed",
      durationMs: 1_200_000,
      createdAt: "Jun 27, 2026",
      createdAtMs: Date.parse("2026-06-27T14:00:00"),
      excerpt: "Audio quality too low for transcription",
      language: "English",
    },
  ],
  details: {},
};
