import pytest
import fathom_core as core
import json

transcript_file = core.data_models.TranscriptFile()

with open('words_object_episode_4973625.json') as f:
    words_object_episode_4973625 = json.load(f)

with open('words_object_episode_4416950.json') as f:
    words_object_episode_4416950 = json.load(f)

with open('sentences_object_episode_4973625.json') as f:
    sentences_object_episode_4973625 = json.load(f)


def test_clip_star_and_end_time_function_with_Deepgram_transcripts():
    '''
    ==================================================================================================
    Testing "clip_star_and_end_time" function with Lex_fridman Deepgram transcript. 
    ==================================================================================================
    '''
    # Clip containing '--' generated by using time_in_seconds = 7655.
    clip_7655 = '''And so mean, it's a it is an interesting question when people talk about your foresightings on all those kinds of things that at least benign aliens. You're thinking of it. benign. Yes. I mean, they -- Mhmm. -- benign, almost curious. Almost partially as with all curiosity, partially selfish to try to observe, is there something interesting about this particular evolutionary system? Because I'm sure even to aliens, earth is a curiosity. Yep. Where it's in as very special stage in as special. Perhaps it's very special. very special. Yes. among the forty five million countries that it's experienced already. So it is a very special time where they should be specially listed.'''

    start, end = transcript_file.clip_star_and_end_time(clip_7655, words_object_episode_4973625)
    assert start == 7644.0 and end == 7688.25

    # 10 random clips.
    clip_2271 = '''Yeah. -- every possible combination of Yeah. That could that could have work. Well, that's not logically impossible. But I think many people would accept that it does go on and contain probably a million times as much stuff. That's what we can see within the horizon. The reason for that incidentally is that if we look as far as we can in one direction and in the opposite direction, Then the conditions don't differ by more than one thousand one hundred thousand. So that means that if we're part of some finite structure, the gradient across the part we can see is very small. And so that suggests that it probably does go on a lot further and the best estimate say, must go on, at least, try to transfer them. Is that exciting or terrifying to you?'''

    start, end = transcript_file.clip_star_and_end_time(clip_2271, words_object_episode_4973625)
    assert start == 2226.6 and end == 2274.68

    clip_54 = '''computers, workstations, laptop, service, cloud compute, all for deep learning. I love Lambda. I won't stop sharing how much I love these systems. They just make it super simple for you to do deep learning. They configure everything for you. I think they have Windows systems, but if you know what's good for you, you're gonna go Linux. Everything works. PyTorch, TensorFlow. Everything is set up. The full stack, it just works.'''

    start, end = transcript_file.clip_star_and_end_time(clip_54, words_object_episode_4973625)
    assert start == 41.65625 and end == 63.03125

    clip_3843 = '''ideas jumping from one person to another over generations -- Yes. -- but we have experiences where we can appreciate beauty and wonder and all that. And a zombie may not have those experiences. Yeah. Or it may have a very different It may have a very black and white harsh description of zot like a philosophical zombie zombie. that could be just a very different way to experience. And, you know, In terms of the explorers that colonized Mars, I I mean, there there's several things I wanna mention. One, it's just at a high level. To me, that's one of the most inspiring things humans can do. is reach out into the unknown. That's in the space of ideas, in the space of science, but also the explorers.'''

    start, end = transcript_file.clip_star_and_end_time(clip_3843, words_object_episode_4973625)
    assert start == 3810.914 and end == 3863.6667

    clip_803 = '''So the important thing is that every science has its own irreducible concepts. in which you get the best explanation. So it may be in chemistry as things like balance in biology, the concept in cell biology, and in the ecology, there are concepts like imprinting, etcetera. and in psychology, there are other concepts. So in a sense, the sciences are like a tall building where you have basic physics, most fundamental, then the rest of physics, then chemistry, then cell biology, etcetera. all the way up to the, I guess, economists and the penthouse and all that. And we have that. And that's true in a sense, but it's not true.'''

    start, end = transcript_file.clip_star_and_end_time(clip_803, words_object_episode_4973625)
    assert start == 793.0 and end == 842.0

    clip_3126 = '''fairly as a topic to have been the first to say. And I think there's a escape clause to that because these entities -- Yeah. -- would be, say, that they evolved by second intent to design, but designed by their predecessors and than designed by us. And whereas Darwinian selection requires two things. it requires aggression and intelligence. This future, intelligent design, may favor intelligence because that's what they were designed for, but it may not favor aggression. And so these future entities, they may be sitting deep thoughts, thinking deep thoughts and not being at all expansionists. So they could be out there. Yeah. And and then we can't refute their existence in the way the family paradox is supposed to refute their existence because These would not be aggressive or expansionist.'''

    start, end = transcript_file.clip_star_and_end_time(clip_3126, words_object_episode_4973625)
    assert start == 3088.9995 and end == 3148.0

def test_clip_star_and_end_time_function_with_rev_ai_clips():
    '''
    ==================================================================================================
    Testing "clip_star_and_end_time" function with Lex_fridman Rev.ai transcript. 
    ==================================================================================================
    '''
    clip_100 = '''And now a quick two-second mention of each sponsor, check them out in the description. That's the best way to support this podcast. We've got give well for charity scale for machine learning on cruise for adventure, by optimizers, for health and athletic greens for performance, she's wisely, my friends and now onto the full lotteries as always no ads in the middle. I try to make these interesting, but if you skip them, please still check out our sponsors. I enjoy their stuff. Maybe you will, too.'''

    start, end = transcript_file.clip_star_and_end_time(clip_100, words_object_episode_4416950)
    assert start == 72.14 and end == 100.82

    clip_5000 = '''So in other words, I'm going to put a gun to your head. I'm going to take your money and I'm going to use it to buy more guns for me to put against your head. But somehow you're going to put a paper in a box and that's going to deactivate my guns. Well, love requires a push and pull there a little bit of tension, a little spice in a relationship. I think, I mean, Hello, gone to some good To anybody. Who's going to be dating you. If you think you're putting a gun to people's head is comfortable to a relationship, All jokes. But yes, I mean, the people don't often think of it has gone to that as government and the military as gun to the head.'''

    start, end = transcript_file.clip_star_and_end_time(clip_5000, words_object_episode_4416950)
    assert start == 4975.17 and end == 5016.19

    clip_9000 = '''There's going to be, it's going to end at some point and we're going to be back at square one, or, well, not in square one. We're going to be back at the same dilemma of who's going to have the global monetary system. And so one alternative is that what the Chinese and the Russians could do is they could base it on a commodity. So a lot of people are not saying, well, they're going to base it on copper and corn and agricultural commodities. And that's, that's the analysis of saleability that we discuss in the base points then in the Fiat standard. That's I don't think that's workable. If you end up basing the monetary system on copper, as we said earlier, it doesn't matter how many governments say that we're going to make a new monetary system based on copper grains and Nicola and Iran. And so on. It doesn't matter.'''

    start, end = transcript_file.clip_star_and_end_time(clip_9000, words_object_episode_4416950)
    assert start == 8977.28 and end == 9024.26

    clip_11000 = '''And this is, this is the absurd thing about this kind of energy scarcity viewpoint where, oh no, it's a catastrophe. Bitcoin is taking all the electricity as if the electricity is just one fixed by that we all have to share and fight over. And this is, it's not, I keep making fun of these stupid headlines. They put out where Bitcoin's consuming more diversity than Portugal. All right, well maybe you should shut down Portugal then what the hell is Portugal given us? Obviously it's not, it's not, Well, it doesn't mean that I've gotten so much criticism for saying Christian out in Kiana of those, not in the top five. I apologize. Ooh. I love that. That's another discussion that we should get into'''

    start, end = transcript_file.clip_star_and_end_time(clip_11000, words_object_episode_4416950)
    assert start == 10991.71 and end == 11029.78

    clip_15000 = '''And my is also a Palestinian refugee from Lebanon. And her family was evicted from Yaffa, which is today on the outskirts of Tel Aviv. They still have their homes in Yaffa. Their homes are being lived. You know, the kid got kicked out of their homes and their lines and their property. They became refugees in Lebanon. So my children, I know it's, it's, it's an ongoing tragedy. It's not something that is a lot of the people that think of it. As you know, they think Palestinians are just out there to get Israelis because they hate them. But it's, it's a, it's an inescapable tragedy. I don't have a home anywhere. Is there an escape from this tragedy in the future that you see, if you zoom out across the scale of decades, will we see, I hesitate to say peace, but a significant decrease in human suffering in this part of the region? I certainly hope so.'''

    start, end = transcript_file.clip_star_and_end_time(clip_15000, words_object_episode_4416950)
    assert start == 14972.95 and end == 15036.51

def test_clip_star_and_end_time_function_with_failed_clips():
    '''
    ==================================================================================================
    Testing function with previous fails. 
    ==================================================================================================
    '''
    # Episode 4973625
    # Lex Fridman Deepgram clip containing '–' generated by using time_in_seconds = 7655.
    # The character U+2013 "–" could be confused with the character U+002d "-", which is more common in source code.
    clip_5172 = '''Or it can be sort of slot us slow, let's say, human spaceflight. It could be have been footprints on miles if America gone on spending four percent of the federal budget on the project after -- Yes. -- upon that. And you said Right. There isn't so there were very good reasons, but – and we could have had supersonic flight, but Concord came and went during the fifty years But the reason it didn't progress is not because we realized it's not good for human society. the reason it didn't progress is because it it couldn't make sort of from a capitalist perspective, it couldn't make there there was no short term or long term wafer to make money. So for make make But isn't it? But that's the same mistake.'''

    start, end = transcript_file.clip_star_and_end_time(clip_5172, words_object_episode_4973625)
    assert start == 5155.7363 and end == 5202.9165

    # Episode 4416950
    # Lex Fridman Rev_ai clip containing 'link' and '$'.
    clip_300 = '''I feel the same way about Alaska. Actually. I'm not afraid of the cold. I don't love the cold, but I'm not afraid of it. And there's something about the isolation, the honesty, and the beauty of nature. That is Alaska is just, it humbles the mind. So even for just a little bit of time, maybe it's a good place to visit. You can save $500 on Alaska adventures through June for bookings made within 30 days of departure, go to on cruise.com/pages/lex that's and cruise UN cruise.com/pages/flex.'''

    start, end = transcript_file.clip_star_and_end_time(clip_300, words_object_episode_4416950)
    assert start == 274.03 and end == 313.6

    # Episode 4416950
    # Lex Fridman Rev_ai clip containing '%'.
    clip_2000 = '''So, you know, there will be a lot more copper mining than all the other methods. A lot of, you know, nickel companies and gold miners are going to switch to focusing on copper, and then we're gonna dump an enormous amount of copper on the market. The value of copper is going to crash and the people who chose copper as money, I'm just going to end up with large warehouses of very cheap rusting metal. So that's a brilliant description. And then that kind of pushes towards gold where the stock to flow ratio, I guess you would say is 1.5 to 2%, like you mentioned earlier. Yeah. Oh, that would be like the inverse of the stock, the flow that's the supply growth rates. So the stock, the flows, the end versus around 60. Got it.'''

    start, end = transcript_file.clip_star_and_end_time(clip_2000, words_object_episode_4416950)
    assert start == 1984.91 and end == 2026.19

    # Episode 4416950
    # Lex Fridman Rev_ai clip containing '$'.
    clip_7000 = '''And then at the end of the day, week or month, you know, banks in the same city, we'll settle with one. Another banks in the same country will settle with one another. And max with different from different countries will settle with one another. So they won't, you know, they won't move the $10 from my account to yours at the end of the day or week or month, they'll tally all of the money that was sent from one bank to the other, and then just settle the difference. So it turns out at the end of the month, my bank had sent $15 million to your bank and your bank had sent $14 million to my bank. So they give them $1 million and that settles it, that finalizes the transaction.'''

    start, end = transcript_file.clip_star_and_end_time(clip_7000, words_object_episode_4416950)
    assert start == 6995.7 and end == 7035.87

def test_optimize_start_end_time_function():
    '''
    ==================================================================================================
    Testing the function with episode 4973625 at time_in_seconds = 2826.

    Transcript chunk for episode 4973625 as reference:
    ..., "So it's the skeptics that ruined a good party.", 'But But we need them, of course.', 'We need them at the party.', 'We need some semantics at the party.', 'Yeah.', 'But boy, would that be so exciting to find life and one of the moons.', 'Yeah.', 'Yeah.',         "because But of course, life That's hopefully the that'll just be any kind of vegetation or life The question of the aliens or science fiction is a different matter.", 'Intelligence aliens.', 'Yeah.', 'Yeah.', "But if if you have a good indication that there's life elsewhere in the solar system.", 'That means life is everywhere.', 'Yep.', 'And that Yep.', "That's that's Yep.", "I don't know if that's terrifying or what that is because if life is everywhere, Why is intelligent life not everywhere?", 'Why?', "I mean, you've talked about them most likely alien civilizations if they are out there.", 'they would likely be far ahead of us, the ones that would actually communicate with us.', 'Yes.', 'And that Again, one of those things is both exciting and terrifying.'          , "You've mentioned that they're likely not to be of biological nature.", ...

    ==================================================================================================
    '''

    clip_2826 = '''The question of the aliens or science fiction is a different matter. Intelligence aliens. Yeah. Yeah. But if if you have a good indication that there's life elsewhere in the solar system. That means life is everywhere. Yep. And that Yep. That's that's Yep. I don't know if that's terrifying or what that is because if life is everywhere, Why is intelligent life not everywhere? Why? I mean, you've talked about them most likely alien civilizations if they are out there. they would likely be far ahead of us, the ones that would actually communicate with us. Yes. And that'''

    start_time, end_time = transcript_file.clip_star_and_end_time(clip_2826, words_object_episode_4973625)
    new_start_time, new_end_time, new_short_clip = transcript_file.optimize_start_end_time(start_time, end_time, sentences_object_episode_4973625)

    assert new_start_time == 2794.0 and new_end_time == 2846.3333 and new_short_clip == "because But of course, life That's hopefully the that'll just be any kind of vegetation or life The question of the aliens or science fiction is a different matter. Intelligence aliens. Yeah. Yeah. But if if you have a good indication that there's life elsewhere in the solar system. That means life is everywhere. Yep. And that Yep. That's that's Yep. I don't know if that's terrifying or what that is because if life is everywhere, Why is intelligent life not everywhere? Why? I mean, you've talked about them most likely alien civilizations if they are out there. they would likely be far ahead of us, the ones that would actually communicate with us. Yes. And that Again, one of those things is both exciting and terrifying."
